"""Initial_Schema

Revision ID: 32246137813a
Revises: 
Create Date: 2026-08-02 01:04:48.118740
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32246137813a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campuses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campuses_code'), 'campuses', ['code'], unique=True)
    op.create_table('class_sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('term_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('lecturer_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='sectionstatus'), nullable=False),
    sa.Column('campus_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_sections_code'), 'class_sections', ['code'], unique=False)
    op.create_index(op.f('ix_class_sections_course_id'), 'class_sections', ['course_id'], unique=False)
    op.create_index(op.f('ix_class_sections_lecturer_id'), 'class_sections', ['lecturer_id'], unique=False)
    op.create_index(op.f('ix_class_sections_term_id'), 'class_sections', ['term_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('major_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    op.create_table('grouping_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('class_section_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mode', sa.Enum('STUDENT_LED', 'LECTURER_LED', 'HYBRID', name='groupingmode'), nullable=False),
    sa.Column('team_min_size', sa.Integer(), nullable=False),
    sa.Column('team_max_size', sa.Integer(), nullable=False),
    sa.Column('required_roles_json', sa.Text(), nullable=False),
    sa.Column('required_skills_json', sa.Text(), nullable=False),
    sa.Column('required_majors_json', sa.Text(), nullable=False),
    sa.Column('allow_cross_major', sa.Boolean(), nullable=False),
    sa.Column('max_same_major_count', sa.Integer(), nullable=False),
    sa.Column('weights_json', sa.Text(), nullable=False),
    sa.Column('profile_deadline', sa.DateTime(), nullable=True),
    sa.Column('self_formation_deadline', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'FROZEN', 'MATCHING', 'REVIEW', 'PUBLISHED', 'CLOSED', 'CANCELLED', name='groupingsessionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grouping_sessions_class_section_id'), 'grouping_sessions', ['class_section_id'], unique=False)
    op.create_index(op.f('ix_grouping_sessions_status'), 'grouping_sessions', ['status'], unique=False)
    op.create_table('majors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('program_id', sa.String(), nullable=False),
    sa.Column('campus_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_majors_campus_id'), 'majors', ['campus_id'], unique=False)
    op.create_index(op.f('ix_majors_code'), 'majors', ['code'], unique=False)
    op.create_table('programs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('campus_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_campus_id'), 'programs', ['campus_id'], unique=False)
    op.create_index(op.f('ix_programs_code'), 'programs', ['code'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('member_ids_json', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('scores_json', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FORMING', 'INCOMPLETE', 'VALID', 'SUBMITTED', 'APPROVED', 'PUBLISHED', 'REJECTED', 'AT_RISK', 'DISSOLVED', 'CLOSED', 'AI_SUGGESTED', name='teamstatus'), nullable=False),
    sa.Column('health_status', sa.Enum('GREEN', 'YELLOW', 'RED', name='healthstatus'), nullable=False),
    sa.Column('leader_id', sa.String(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('project_topic', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_session_id'), 'teams', ['session_id'], unique=False)
    op.create_index(op.f('ix_teams_status'), 'teams', ['status'], unique=False)
    op.create_table('terms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campus_id', sa.String(), nullable=False),
    sa.Column('academic_year_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'CLOSED', 'ARCHIVED', name='termstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terms_campus_id'), 'terms', ['campus_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'LECTURER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('user_status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus'), nullable=False),
    sa.Column('student_code', sa.String(), nullable=False),
    sa.Column('campus_id', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_campus_id'), 'users', ['campus_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_student_code'), 'users', ['student_code'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('current_task', sa.Text(), nullable=False),
    sa.Column('workload', sa.String(), nullable=False),
    sa.Column('collaboration_rating', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=False),
    sa.Column('support_requested', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_student_id'), 'checkins', ['student_id'], unique=False)
    op.create_index(op.f('ix_checkins_team_id'), 'checkins', ['team_id'], unique=False)
    op.create_table('join_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='joinrequeststatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_join_requests_student_id'), 'join_requests', ['student_id'], unique=False)
    op.create_index(op.f('ix_join_requests_team_id'), 'join_requests', ['team_id'], unique=False)
    op.create_table('risk_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_alerts_session_id'), 'risk_alerts', ['session_id'], unique=False)
    op.create_index(op.f('ix_risk_alerts_team_id'), 'risk_alerts', ['team_id'], unique=False)
    op.create_table('team_dnas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('class_section_id', sa.String(), nullable=False),
    sa.Column('skills_json', sa.Text(), nullable=False),
    sa.Column('preferred_roles_json', sa.Text(), nullable=False),
    sa.Column('experiences_json', sa.Text(), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=False),
    sa.Column('availability_json', sa.Text(), nullable=False),
    sa.Column('interests_json', sa.Text(), nullable=False),
    sa.Column('commitment_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='commitmentlevel'), nullable=False),
    sa.Column('working_preferences_json', sa.Text(), nullable=False),
    sa.Column('portfolio_url', sa.String(), nullable=False),
    sa.Column('preferred_team_size', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_dnas_class_section_id'), 'team_dnas', ['class_section_id'], unique=False)
    op.create_index(op.f('ix_team_dnas_student_id'), 'team_dnas', ['student_id'], unique=False)
    op.create_table('team_invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('from_student_id', sa.String(), nullable=False),
    sa.Column('to_student_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELLED', 'EXPIRED', name='invitationstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['to_student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_invitations_from_student_id'), 'team_invitations', ['from_student_id'], unique=False)
    op.create_index(op.f('ix_team_invitations_team_id'), 'team_invitations', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_invitations_to_student_id'), 'team_invitations', ['to_student_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'APPLIED', 'ACTIVE', 'LEAVE_REQUESTED', 'REMOVAL_REQUESTED', 'WITHDRAWN', 'REMOVED', 'REJECTED', name='membershipstatus'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_student_id'), 'team_members', ['student_id'], unique=False)
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_table('vacancies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('required_role', sa.String(), nullable=False),
    sa.Column('required_major', sa.String(), nullable=False),
    sa.Column('required_skill', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancies_team_id'), 'vacancies', ['team_id'], unique=False)
    op.drop_table('formation_teams')
    op.drop_index(op.f('ix_audit_events_cohort_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_student_constraints_cohort_id'), table_name='student_constraints')
    op.drop_table('student_constraints')
    op.drop_table('student_skills')
    op.drop_index(op.f('ix_formation_runs_cohort_id'), table_name='formation_runs')
    op.drop_table('formation_runs')
    op.drop_index(op.f('ix_cohorts_owner_id'), table_name='cohorts')
    op.drop_table('cohorts')
    op.drop_index(op.f('ix_committed_results_cohort_id'), table_name='committed_results')
    op.drop_table('committed_results')
    op.drop_table('enrollments')
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('major', sa.VARCHAR(), nullable=False),
    sa.Column('experience_years', sa.FLOAT(), nullable=False),
    sa.Column('desired_role', sa.VARCHAR(), nullable=False),
    sa.Column('availability', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(), nullable=False),
    sa.Column('cohort_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('committed_results',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('cohort_id', sa.VARCHAR(), nullable=False),
    sa.Column('formation_id', sa.VARCHAR(), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('committed_by', sa.VARCHAR(), nullable=False),
    sa.Column('committed_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committed_results_cohort_id'), 'committed_results', ['cohort_id'], unique=False)
    op.create_table('cohorts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('owner_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cohorts_owner_id'), 'cohorts', ['owner_id'], unique=False)
    op.create_table('formation_runs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('cohort_id', sa.VARCHAR(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('min_size', sa.INTEGER(), nullable=False),
    sa.Column('max_size', sa.INTEGER(), nullable=False),
    sa.Column('seed', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('balance', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formation_runs_cohort_id'), 'formation_runs', ['cohort_id'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(), nullable=False),
    sa.Column('skill_name', sa.VARCHAR(), nullable=False),
    sa.Column('proficiency', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_constraints',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('cohort_id', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('student_a', sa.VARCHAR(), nullable=False),
    sa.Column('student_b', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_constraints_cohort_id'), 'student_constraints', ['cohort_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cohort_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('payload', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_cohort_id'), 'audit_events', ['cohort_id'], unique=False)
    op.create_table('formation_teams',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('formation_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('rationale', sa.VARCHAR(), nullable=False),
    sa.Column('member_ids', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['formation_id'], ['formation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_vacancies_team_id'), table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_student_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_team_invitations_to_student_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_team_id'), table_name='team_invitations')
    op.drop_index(op.f('ix_team_invitations_from_student_id'), table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index(op.f('ix_team_dnas_student_id'), table_name='team_dnas')
    op.drop_index(op.f('ix_team_dnas_class_section_id'), table_name='team_dnas')
    op.drop_table('team_dnas')
    op.drop_index(op.f('ix_risk_alerts_team_id'), table_name='risk_alerts')
    op.drop_index(op.f('ix_risk_alerts_session_id'), table_name='risk_alerts')
    op.drop_table('risk_alerts')
    op.drop_index(op.f('ix_join_requests_team_id'), table_name='join_requests')
    op.drop_index(op.f('ix_join_requests_student_id'), table_name='join_requests')
    op.drop_table('join_requests')
    op.drop_index(op.f('ix_checkins_team_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_student_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_users_student_code'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_campus_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_terms_campus_id'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_teams_status'), table_name='teams')
    op.drop_index(op.f('ix_teams_session_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_programs_code'), table_name='programs')
    op.drop_index(op.f('ix_programs_campus_id'), table_name='programs')
    op.drop_table('programs')
    op.drop_index(op.f('ix_majors_code'), table_name='majors')
    op.drop_index(op.f('ix_majors_campus_id'), table_name='majors')
    op.drop_table('majors')
    op.drop_index(op.f('ix_grouping_sessions_status'), table_name='grouping_sessions')
    op.drop_index(op.f('ix_grouping_sessions_class_section_id'), table_name='grouping_sessions')
    op.drop_table('grouping_sessions')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_class_sections_term_id'), table_name='class_sections')
    op.drop_index(op.f('ix_class_sections_lecturer_id'), table_name='class_sections')
    op.drop_index(op.f('ix_class_sections_course_id'), table_name='class_sections')
    op.drop_index(op.f('ix_class_sections_code'), table_name='class_sections')
    op.drop_table('class_sections')
    op.drop_index(op.f('ix_campuses_code'), table_name='campuses')
    op.drop_table('campuses')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
